# Generated by Django 5.0.3 on 2024-03-06 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computacion_api', '0002_administradores_delete_profiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alummos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('clave_alumno', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_nacimiento', models.DateTimeField(blank=True, null=True)),
                ('curp', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=255, null=True)),
                ('rfc', models.CharField(blank=True, max_length=255, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('ocupacion', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
