# Generated by Django 5.0.3 on 2024-05-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computacion_api', '0005_rename_alummos_alumnos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nrc', models.CharField(blank=True, max_length=255, null=True)),
                ('seccion', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('horaInicio', models.CharField(blank=True, max_length=255, null=True)),
                ('horaFinal', models.CharField(blank=True, max_length=255, null=True)),
                ('dias', models.CharField(blank=True, max_length=255, null=True)),
                ('salon', models.CharField(blank=True, max_length=255, null=True)),
                ('programa', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
